-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;

DROP TABLE IF EXISTS azayca.viaje CASCADE;
DROP TABLE IF EXISTS azayca.conductor CASCADE;
DROP TABLE IF EXISTS azayca.empresa_transporte CASCADE;
DROP TABLE IF EXISTS azayca.provincia CASCADE;
DROP TABLE IF EXISTS azayca.localidad CASCADE;
DROP TABLE IF EXISTS azayca.localizacion CASCADE;
DROP TABLE IF EXISTS azayca.tarifa CASCADE;
DROP TABLE IF EXISTS azayca.socio CASCADE;
DROP TABLE IF EXISTS azayca.usuario CASCADE;

CREATE TABLE IF NOT EXISTS azayca.conductor
(
    id serial NOT NULL,
    nombre character varying(40) COLLATE pg_catalog."default" NOT NULL,
    apellido1 character varying(40) COLLATE pg_catalog."default" NOT NULL,
    apellido2 character varying(40) COLLATE pg_catalog."default",
    nif character varying(12) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta date NOT NULL,
    id_empresa integer,
    CONSTRAINT pk_conductor PRIMARY KEY (id),
    CONSTRAINT "uk_conductor.nif" UNIQUE (nif)
);

CREATE TABLE IF NOT EXISTS azayca.empresa_transporte
(
    id serial NOT NULL,
    nombre character varying(60) COLLATE pg_catalog."default" NOT NULL,
    cif character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "nombreResponsable" character varying(60) COLLATE pg_catalog."default",
    telefono integer,
    email character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT pk_empresa_transporte PRIMARY KEY (id),
    CONSTRAINT "uk_empresa_transporte.cif" UNIQUE (cif)
);

CREATE TABLE IF NOT EXISTS azayca.localidad
(
    id serial NOT NULL,
    nombre character varying(40) COLLATE pg_catalog."default" NOT NULL,
    id_provincia integer NOT NULL,
    CONSTRAINT pk_localidad PRIMARY KEY (id),
    CONSTRAINT uk_localidad UNIQUE (nombre, id_provincia)
);

CREATE TABLE IF NOT EXISTS azayca.localizacion
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_localidad integer NOT NULL,
    CONSTRAINT pk_localizacion PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS azayca.provincia
(
    id serial NOT NULL,
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_provincia PRIMARY KEY (id),
    CONSTRAINT "uk_provincia.nombre" UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS azayca.socio
(
    id serial NOT NULL,
    nombre character varying(40) COLLATE pg_catalog."default" NOT NULL,
    apellido1 character varying(40) COLLATE pg_catalog."default" NOT NULL,
    apellido2 character varying(40) COLLATE pg_catalog."default",
    email character varying(40) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta date NOT NULL,
    telefono integer NOT NULL,
    telefono2 integer,
    dni character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_socio PRIMARY KEY (id),
    CONSTRAINT "uk_socio.dni" UNIQUE (dni)
);

CREATE TABLE IF NOT EXISTS azayca.tarifa
(
    id serial NOT NULL,
    id_compania integer NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    unidad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(2, 0),
    CONSTRAINT pk_tarifa PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS azayca.usuario
(
    id serial NOT NULL,
    login character varying(15) COLLATE pg_catalog."default" NOT NULL,
    password character(256) COLLATE pg_catalog."default" NOT NULL,
    email character varying(40) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT "uk_usuario.login" UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS azayca.viaje
(
    id serial NOT NULL,
    fecha time without time zone NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    id_socio integer NOT NULL,
    id_conductor integer NOT NULL,
    id_tarifa integer NOT NULL,
    id_localizacion_origen integer NOT NULL,
    id_localizacion_destino integer NOT NULL,
    id_viaje_relacionado integer,
    importe numeric NOT NULL,
    CONSTRAINT pk_viaje PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS azayca.conductor
    ADD CONSTRAINT "fk_conductor.empresa" FOREIGN KEY (id_empresa)
        REFERENCES azayca.empresa_transporte (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.localidad
    ADD CONSTRAINT "fk_localidad.provincia" FOREIGN KEY (id_provincia)
        REFERENCES azayca.provincia (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.localizacion
    ADD CONSTRAINT fk_localidad FOREIGN KEY (id_localidad)
        REFERENCES azayca.localidad (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "fk_viaje.conductor" FOREIGN KEY (id_conductor)
        REFERENCES azayca.conductor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "fk_viaje.localizacion_destino" FOREIGN KEY (id_localizacion_destino)
        REFERENCES azayca.localizacion (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "fk_viaje.localizacion_origen" FOREIGN KEY (id_localizacion_origen)
        REFERENCES azayca.localizacion (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "fk_viaje.tarifa" FOREIGN KEY (id_tarifa)
        REFERENCES azayca.tarifa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "fk_viajes.relacionado" FOREIGN KEY (id_viaje_relacionado)
        REFERENCES azayca.viaje (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS azayca.viaje
    ADD CONSTRAINT "pk_viaje.socio" FOREIGN KEY (id_socio)
        REFERENCES azayca.socio (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;


INSERT INTO azayca.usuario(login, password, email) VALUES ('manolo', '1234', 'manolo@gmail.com');